name: "Translation / 翻訳 / 翻譯"
description: "Suggest translation improvements / 翻訳改善の提案 / 翻譯改進建議"
title: "[Translation] "
labels: ["translation"]
body:
  - type: dropdown
    id: language
    attributes:
      label: "Language / 言語 / 語言"
      description: "Which language needs improvement? / どの言語を改善しますか？ / 需要改進哪個語言？"
      options:
        - 日本語
        - 繁體中文
        - English
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: "Location / 場所 / 位置"
      description: "Which file or UI element? (e.g., assets/locales/ja.json, header text) / どのファイルまたはUI要素？ / 哪個檔案或 UI 元素？"
      placeholder: "e.g., assets/locales/ja.json or 'Submit button text'"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: "Current text / 現在のテキスト / 目前文字"
      description: "What is the current translation? / 現在の翻訳は？ / 目前的翻譯是什麼？"
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: "Suggested text / 提案 / 建議文字"
      description: "What should it be changed to? / どう変更すべきですか？ / 建議改成什麼？"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Reason / 理由 / 原因"
      description: "Why is this change better? (optional) / なぜこの変更が良いですか？（任意）/ 為什麼這個改動比較好？（選填）"
    validations:
      required: false
